### ISSUE TITLE
Pump activity during a network problem, gets overlooked...

### ISSUE THREAD

**Issue by gantonel** [MasterMartbob/tplink-hs110-pump-monitor#4]
We have already mentioned that the cloud API has not been very reliable. I am now noticing some issues even with the local API, but at least it has not yet caused a complete stop of our software.
I am getting some errors of this type
[2020-04-17T17:10:48.632] [INFO] debug - Error: connect ENETDOWN 192.168.0.5:9999 - Local (192.168.0.8:56734)
192.168.0.5 has been assigned to the pump, and 192.168.0.8 is the laptop from which the software is run
I do not know what causes the ENETDOWN error, but here is the ISSUE

When the pump is active during a network "blackout" it does not get reported.
The missing activity could be reported if we considered reporting changes to the energy consumed

Here are lines from the debug log ( they have NOT been modified by me!)

[2020-04-17T22:10:06.398] [INFO] debug - {"voltage_mv":235542,"current_ma":18,"power_mw":0,"total_wh":109,"err_code":0,"current":0.018,"power":0,"total":0.109,"voltage":235.542}
[2020-04-17T22:10:16.590] [INFO] debug - {"voltage_mv":235503,"current_ma":18,"power_mw":0,"total_wh":109,"err_code":0,"current":0.018,"power":0,"total":0.109,"voltage":235.503}
[2020-04-17T22:10:26.750] [INFO] debug - {"voltage_mv":234903,"current_ma":18,"power_mw":0,"total_wh":109,"err_code":0,"current":0.018,"power":0,"total":0.109,"voltage":234.903}
[2020-04-17T22:10:36.911] [INFO] debug - {"voltage_mv":235566,"current_ma":18,"power_mw":0,"total_wh":109,"err_code":0,"current":0.018,"power":0,"total":0.109,"voltage":235.566}
[2020-04-17T22:10:47.069] [INFO] debug - {"voltage_mv":235471,"current_ma":18,"power_mw":0,"total_wh":109,"err_code":0,"current":0.018,"power":0,"total":0.109,"voltage":235.471}
[2020-04-17T22:10:57.375] [INFO] debug - {"voltage_mv":235264,"current_ma":18,"power_mw":0,"total_wh":109,"err_code":0,"current":0.018,"power":0,"total":0.109,"voltage":235.264}
[2020-04-17T22:11:07.571] [INFO] debug - {"voltage_mv":235454,"current_ma":18,"power_mw":0,"total_wh":109,"err_code":0,"current":0.018,"power":0,"total":0.109,"voltage":235.454}
[2020-04-17T22:11:19.160] [INFO] debug - {"voltage_mv":235494,"current_ma":18,"power_mw":0,"total_wh":109,"err_code":0,"current":0.018,"power":0,"total":0.109,"voltage":235.494}
[2020-04-17T22:11:29.356] [INFO] debug - {"voltage_mv":234773,"current_ma":18,"power_mw":0,"total_wh":109,"err_code":0,"current":0.018,"power":0,"total":0.109,"voltage":234.773}
[2020-04-17T22:11:39.806] [INFO] debug - {"voltage_mv":235011,"current_ma":18,"power_mw":0,"total_wh":109,"err_code":0,"current":0.018,"power":0,"total":0.109,"voltage":235.011}
[2020-04-17T22:11:50.256] [INFO] debug - {"voltage_mv":235131,"current_ma":18,"power_mw":0,"total_wh":109,"err_code":0,"current":0.018,"power":0,"total":0.109,"voltage":235.131}
[2020-04-17T22:12:00.432] [INFO] debug - {"voltage_mv":234716,"current_ma":18,"power_mw":0,"total_wh":109,"err_code":0,"current":0.018,"power":0,"total":0.109,"voltage":234.716}
[2020-04-18T00:12:07.845] [INFO] debug - {"voltage_mv":234228,"current_ma":18,"power_mw":0,"total_wh":117,"err_code":0,"current":0.018,"power":0,"total":0.117,"voltage":234.228}
[2020-04-18T01:12:08.379] [INFO] debug - {"voltage_mv":232161,"current_ma":18,"power_mw":0,"total_wh":117,"err_code":0,"current":0.018,"power":0,"total":0.117,"voltage":232.161}
[2020-04-18T03:12:19.337] [INFO] debug - Error: connect ENETDOWN 192.168.0.5:9999 - Local (192.168.0.8:59346)
    at internalConnect (net.js:917:16)
    at defaultTriggerAsyncIdScope (internal/async_hooks.js:311:12)
    at net.js:1007:9
    at processTicksAndRejections (internal/process/task_queues.js:79:11) {
  errno: 'ENETDOWN',
  code: 'ENETDOWN',
  syscall: 'connect',
  address: '192.168.0.5',
  port: 9999
}
[2020-04-18T03:12:20.126] [INFO] debug - {"voltage_mv":235207,"current_ma":18,"power_mw":0,"total_wh":117,"err_code":0,"current":0.018,"power":0,"total":0.117,"voltage":235.207}
[2020-04-18T05:12:33.117] [INFO] debug - {"voltage_mv":235414,"current_ma":18,"power_mw":0,"total_wh":117,"err_code":0,"current":0.018,"power":0,"total":0.117,"voltage":235.414}
[2020-04-18T05:12:43.450] [INFO] debug - {"voltage_mv":233649,"current_ma":18,"power_mw":0,"total_wh":117,"err_code":0,"current":0.018,"power":0,"total":0.117,"voltage":233.649}
[2020-04-18T05:12:53.622] [INFO] debug - {"voltage_mv":233559,"current_ma":18,"power_mw":0,"total_wh":117,"err_code":0,"current":0.018,"power":0,"total":0.117,"voltage":233.559}

The change from "total_wh":109 to "total_wh":117 means that the pump was on between
[2020-04-17T22:12:00.432]  &  
[2020-04-18T00:12:07.845]

If it were to become a feature, the activity could be reported at the time we first noticed it and give the pump start and pump stop emails the same time!

Maybe this is not really an issue.
Maybe I just wanted to continue the conversation.

BTW I think your coding skills are excellent and I am loving my/your **tplink-hs110-pump-monitor** !

**Comment by mchenier** [comment]
Thanks for the feedback but Im not sure either that this is a feature I want. It would get complicated very quickly if you had multiple start stop in a down period.

I'll keep that in mind tough if I got more time to work on the project. But now it seams pretty much like I wanted. Only think remaining for me would be a more easy way to get the graph I want but didn't have time for that.

**Comment by gantonel** [comment]
Perfectly understandable.
I am happy for this issue to be closed off.
I am not sure of the etiquette, do I close it off or do you?
