### ISSUE TITLE
New error and email not sent

### ISSUE THREAD

**Issue by gantonel** [MasterMartbob/tplink-hs110-pump-monitor#5]
I have not received an email, even though the debug log implies that the pump was active. Here are the relevant log lines

[2020-04-24T00:58:41.386] [INFO] debug - {"voltage_mv":231862,"current_ma":1376,"power_mw":291675,"**total_wh":126**,"err_code":0,"current":1.376,"power":291.675,"total":0.126,"voltage":231.862}
[2020-04-24T00:58:41.387] [INFO] default - **Pump Started**
(node:10149) UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'getDayStats' of undefined
    at getHistoryStat (/Users/giorgioantonelli/tplink-hs110-pump-monitor/utils.js:108:25)
    at Object.sendEmail (/Users/giorgioantonelli/tplink-hs110-pump-monitor/utils.js:71:48)
(node:10149) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 2)
(node:10149) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
[2020-04-24T00:58:51.690] [INFO] debug - {"voltage_mv":231535,"current_ma":1348,"power_mw":284138,"total_wh":127,"err_code":0,"current":1.348,"power":284.138,"total":0.127,"voltage":231.535}
[2020-04-24T00:59:01.995] [INFO] debug - {"voltage_mv":231690,"current_ma":1332,"power_mw":280511,"total_wh":128,"err_code":0,"current":1.332,"power":280.511,"total":0.128,"voltage":231.69}
[2020-04-24T00:59:12.297] [INFO] debug - {"voltage_mv":231662,"current_ma":1322,"power_mw":277435,"total_wh":128,"err_code":0,"current":1.322,"power":277.435,"total":0.128,"voltage":231.662}
[2020-04-24T00:59:22.468] [INFO] debug - {"voltage_mv":231600,"current_ma":1308,"power_mw":273682,"total_wh":129,"err_code":0,"current":1.308,"power":273.682,"total":0.129,"voltage":231.6}
[2020-04-24T00:59:32.772] [INFO] debug - {"voltage_mv":231206,"current_ma":1298,"power_mw":270874,"total_wh":130,"err_code":0,"current":1.298,"power":270.874,"total":0.13,"voltage":231.206}
[2020-04-24T00:59:43.076] [INFO] debug - {"voltage_mv":231607,"current_ma":1295,"power_mw":269834,"total_wh":131,"err_code":0,"current":1.295,"power":269.834,"total":0.131,"voltage":231.607}
[2020-04-24T00:59:53.380] [INFO] debug - {"voltage_mv":231616,"current_ma":1287,"power_mw":268165,"total_wh":132,"err_code":0,"current":1.287,"power":268.165,"total":0.132,"voltage":231.616}
[2020-04-24T01:00:03.683] [INFO] debug - {"voltage_mv":231566,"current_ma":1280,"power_mw":266078,"total_wh":132,"err_code":0,"current":1.28,"power":266.078,"total":0.132,"voltage":231.566}
[2020-04-24T01:00:13.987] [INFO] debug - {"voltage_mv":232775,"current_ma":18,"power_mw":0,"**total_wh":133**,"err_code":0,"current":0.018,"power":0,"total":0.133,"voltage":232.775}
[2020-04-24T01:00:13.988] [INFO] debug - **ReferenceError: utils is not defined**
    at Object.saveGraphData (/Users/giorgioantonelli/tplink-hs110-pump-monitor/utils.js:92:16)
    at Object.stopDevice (/Users/giorgioantonelli/tplink-hs110-pump-monitor/app.js:43:11)
    at verifyStartStop (/Users/giorgioantonelli/tplink-hs110-pump-monitor/app.js:96:21)
    at monitoring (/Users/giorgioantonelli/tplink-hs110-pump-monitor/app.js:76:5)
    at main (/Users/giorgioantonelli/tplink-hs110-pump-monitor/app.js:61:7)
[2020-04-24T01:00:24.178] [INFO] debug - {"voltage_mv":232643,"current_ma":18,"power_mw":0,"**total_wh":133**,"err_code":0,"current":0.018,"power":0,"total":0.133,"voltage":232.643}

**Comment by vdasilva** [comment]
@gantonel are you running latest version? There was a fix related to an email bug a few days ago.

**Comment by gantonel** [comment]
I thought I was running the latest, but I will check.
I don’t recall an email bug fix

Thanks

**Comment by mchenier** [comment]
Yes that's true. I had the same problem. 
Sorry for that.

I have to update the release package too I didn't have the time.
But latest code should work.

**Comment by gantonel** [comment]
Thank you.
You were correct.
It looks like there was a “Fix bug with the email” a few days ago.
I was under the impression we’d be notified of such activity but I am new on GitHub

**Comment by vdasilva** [comment]
Guys, if you're interested, I've played around with merging this project's functionality to jamesbarnett91/tplink-energy-monitor charting interface. It's a work in progress with the following issues:
1. Need to fix up documentation
2. Add ability to handle multiple plugs (partly there - works ok with one plug
3. Add logging back into the project and email
4. Package up into executable files
 
The revised project is in my repo at: https://github.com/vdasilva/tplink-energy-monitor

To get it configured, rename "[ID]-monitor-config-example.json" to remove "-example" and replace [ID] with your plug's ID - this is a long number such as "8006A66AC0798311B89668AE7EA89C501C973858". Once you let the application run for the first time, it will create a log file with that ID in the file name - I just copied it from there... Next, configure your parameters (email, password, setpoints etc.

I'm sure it's full of errors but I've enjoyed playing around with this and learning about JS, express and github.

cheers!

**Comment by mchenier** [comment]
@vdasilva @gantonel 
Wanted to notice you that I have worked on a little UI for the project.
Let me know what you think.

**Comment by gantonel** [comment]
Many thanks.
I am not at home, so I will let you know as soon as I can in a few days.

Regards

Giorgio

**Comment by vdasilva** [comment]
It looks pretty cool! Well done. I've moved away from using this application and instead now use Home Assistant (there's an interface for these TPLink plugs) together with Node Red to give me charting and custom emailing as required.
Thanks for your help along the way - this has been a fun learning excercise for me!

Edit: check this out: https://youtu.be/9ViLqLne7-4

**Comment by gantonel** [comment]
Hi,

I have tried to install the new version of the software.
I transferred to the new folder the config file AND the log files.
I think the log files may not be named correctly according to the UI.

I would appreciate it if you would let me know how to name the files or at least how to take the historical data to the new folder

Regards

Giorgio

**Comment by mchenier** [comment]
I'm not at home but it should be auto generated in ui
assets/device_graph.csv
